version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: teamatldocker/jira
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://${POSTGRESUSER}@postgresql/${POSTGRESDB}'
      - 'JIRA_DB_PASSWORD=${POSTGRESPASSWORD}'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME=${JIRAPROXYNAME}'
      - 'JIRA_PROXY_PORT=${JIRAPROXYPORT}'
      - 'JIRA_PROXY_SCHEME=${JIRAPROXYSCHEME}'
volumes:
  jiradata:
    external: false

networks:
  jiranet:
    driver: bridge