version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: teamatldocker/jira
    container_name: jira
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://${POSTGRESUSER}@postgresql/${POSTGRESDB}'
      - 'JIRA_DB_PASSWORD=${POSTGRESPASSWORD}'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME=${JIRAPROXYNAME}'
      - 'JIRA_PROXY_PORT=${JIRAPROXYPORT}'
      - 'JIRA_PROXY_SCHEME=${JIRAPROXYSCHEME}'
  confluence:
    image: eugenmayer/confluence
    container_name: confluence
    volumes:
      - confluencedata:/var/atlassian/confluence
    ports:
      - '8081:8090'
      #- '8091:8091'
    environment:
      - CONFLUENCE_DB_HOST=postgresql
      - CONFLUENCE_DB_PORT=5432
      - CATALINA_OPTS=-Xms256m -Xmx1g
      - CONFLUENCE_PROXY_NAME=${CONFPROXYNAME}
      - CONFLUENCE_PROXY_PORT=${CONFPROXYPORT}
      - CONFLUENCE_PROXY_SCHEME=${CONFPROXYSCHEME}
      - CONFLUENCE_DELAYED_START=
      - CONFLUENCE_CONFIG_PROPERTY1=hibernate.connection.driver_class
      - CONFLUENCE_CONFIG_VALUE1=org.postgresql.Driver
      - CONFLUENCE_CONFIG_PROPERTY2=hibernate.connection.password
      - CONFLUENCE_CONFIG_VALUE2=jellyfish
      - CONFLUENCE_CONFIG_PROPERTY3=hibernate.connection.url
      - CONFLUENCE_CONFIG_VALUE3=jdbc:${POSTGRESUSER}@postgresql/${POSTGRESDB2}
      - CONFLUENCE_CONFIG_PROPERTY4=hibernate.connection.username
      - CONFLUENCE_CONFIG_VALUE4=confluencedb
    depends_on:
      - postgresql
    networks:
      - jiranet
  postgresql:
    image: postgres:9.5-alpine
    container_name: postgresql
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=${POSTGRESUSER}'
      - 'POSTGRES_PASSWORD=${POSTGRESPASSWORD}'
      - 'POSTGRES_DB=${POSTGRESDB}'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
  confluencedata:
    external: false

networks:
  jiranet:
    driver: bridge
