version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: teamatldocker/jira
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://${POSTGRESUSER}@postgresql/${POSTGRESDB}'
      - 'JIRA_DB_PASSWORD=${POSTGRESPASSWORD}'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME=${JIRAPROXYNAME}'
      - 'JIRA_PROXY_PORT=${JIRAPROXYPORT}'
      - 'JIRA_PROXY_SCHEME=${JIRAPROXYSCHEME}'
  postgresql:
    image: postgres:9.5-alpine
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=${POSTGRESUSER}'
      - 'POSTGRES_PASSWORD=${POSTGRESPASSWORD}'
      - 'POSTGRES_DB=${POSTGRESDB}'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge